version: "2.17.2"

services:
  mongodb:
    container_name: database_contianer
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  
  app:
    build: .
    ports:
      - 3000:8080
    environment:
        MONGO_LOCAL_CONN_URL : mongodb://mongodb:27017/wuhdet
    depends_on:
      - mongodb
volumes:
  mongodb : {}


