version: "2.17.2"

services:
  mongodb:
    container_name: database_contianer
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
  
  app:
    build: .
    ports:
      - 3000:8080
    environment:
        EMAIL : mahider3991@gmail.com
        MAIL_USERNAME :  mahider3991@gmail.com
        MAIL_PASSWORD : Maverick2020!
        OAUTH_CLIENTID : 362464437456-eqjc2n35ife74b6d5sb28e49qc0hbc06.apps.googleusercontent.com
        OAUTH_CLIENT_SECRET : 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
        OAUTH_REFRESH_TOKEN : 1//04-97x4jHIuiLCgYIARAAGAQSNwF-L9Irf0LdH6ZFPb7y8-3FAEbRJcD2MWqom_ml5U-wdN4b6bWi1M7Dbizp2qwNMDjKlAx6mCc
        JWT_SECRET : jwtsecret
        MONGO_LOCAL_CONN_URL : mongodb://mongodb:27017/wuhdet
        CLOUD_NAME : dytequc2m
        CLOUD_API_KEY : 283248446939275
        CLOUD_API_SECRET : uFJhxNAJlCeLqQbSqp8-pV3H7lE
    depends_on:
      - mongodb
volumes:
  mongodb : {}


